<?php
session_start();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to NutriLift</title>
    <link rel="stylesheet" href="styles.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>
<body>
    <?php include 'header.php'; ?>

    <!-- Hero Section -->
    <section class="hero">
        <div class="container">
            <h1>Elevate Your Nutrition</h1>
            <p>Personalized AI-based meal planning for healthy weight gain.</p>
            <?php if (!isset($_SESSION['user_id'])): ?>
                <a href="signup.php" class="btn btn-primary">Get Started Now</a>
            <?php else: ?>
                <a href="profile.php" class="btn btn-primary">Go to Profile</a>
            <?php endif; ?>
        </div>
    </section>

    <!-- What to Expect Section -->
    <main class="container">
        <section class="features-section">
            <h2>What to Expect</h2>
            <p>NutriLift is designed to help you gain weight in a healthy, sustainable way. Here’s a preview of the tools and features waiting for you.</p>
            <div class="features-grid">
                <!-- Feature 1: User Profile -->
                <div class="feature-card">
                    <i class="fas fa-user-circle feature-icon"></i>
                    <h3>Personalized Profile</h3>
                    <p>Create your profile with details like your weight goal, dietary preferences, and allergies. NutriLift tailors everything to your unique needs.</p>
                </div>
                <!-- Feature 2: Meal Plan Generator -->
                <div class="feature-card">
                    <i class="fas fa-utensils feature-icon"></i>
                    <h3>AI-Powered Meal Plans</h3>
                    <p>Get weekly meal plans generated by our AI, designed to help you meet your calorie and nutrition goals with delicious, healthy meals.</p>
                </div>
                <!-- Feature 3: Nutritional Analysis -->
                <div class="feature-card">
                    <i class="fas fa-chart-pie feature-icon"></i>
                    <h3>Nutritional Analysis</h3>
                    <p>Understand your meals with detailed breakdowns of calories, carbs, protein, and fats, ensuring you’re on track for healthy weight gain.</p>
                </div>
                <!-- Feature 4: Shopping List -->
                <div class="feature-card">
                    <i class="fas fa-shopping-cart feature-icon"></i>
                    <h3>Smart Shopping List</h3>
                    <p>Automatically generate a shopping list based on your meal plans, making grocery trips quick and easy.</p>
                </div>
                <!-- Feature 5: Progress Tracker -->
                <div class="feature-card">
                    <i class="fas fa-weight feature-icon"></i>
                    <h3>Progress Tracker</h3>
                    <p>Track your weight gain journey with easy-to-use tools, helping you stay motivated and monitor your success.</p>
                </div>
            </div>
        </section>

        <!-- Why NutriLift Section -->
        <section class="why-nutrilift">
            <h2>Why NutriLift?</h2>
            <div class="why-content">
                <div class="why-text">
                    <p>NutriLift is your partner in achieving healthy weight gain, especially for underweight individuals like breastfeeding mothers. Our AI-driven system creates weekly meal plans tailored to your dietary preferences and allergies, provides detailed nutritional analysis, and even generates a shopping list to simplify your journey. With NutriLift, you’ll have all the tools you need to nourish your body and reach your goals.</p>
                    <a href="signup.php" class="btn btn-primary">Start Your Journey</a>
                </div>
                <div class="why-image">
                    <img src="https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" alt="Healthy Meal">
                </div>
            </div>
        </section>
    </main>

    <?php include 'footer.php'; ?>
    <script src="script.js"></script>
</body>
</html>